#include "Flight/Born2FlapWingMesh.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Engine/Texture2D.h"

namespace
{
// Kestrel membrane outline (kestrelwing.svg "wingmembrane shape"), mapped to
// mesh space: Y = span (0 root -> 100 tip), X = chordwise (LE forward/positive,
// TE aft/negative). Generated by Tools/build_kestrel_wing_textures.py.
const FVector2D MembraneLE[13] = {
    FVector2D(0.0000, 8.9537), FVector2D(8.3333, 1.8829), FVector2D(16.6667, 0.4742),
    FVector2D(25.0000, 0.2523), FVector2D(33.3333, 0.0303), FVector2D(41.6667, -0.1917),
    FVector2D(50.0000, -0.8824), FVector2D(58.3333, -1.7554), FVector2D(66.6667, -2.6284),
    FVector2D(75.0000, -3.5014), FVector2D(83.3333, -4.3744), FVector2D(91.6667, -5.2475),
    FVector2D(100.0000, -6.1205),
};
const FVector2D MembraneTE[13] = {
    FVector2D(0.0000, -38.3238), FVector2D(8.3333, -35.2478), FVector2D(16.6667, -34.5084),
    FVector2D(25.0000, -33.7690), FVector2D(33.3333, -33.0296), FVector2D(41.6667, -32.2902),
    FVector2D(50.0000, -30.8563), FVector2D(58.3333, -29.4212), FVector2D(66.6667, -27.9861),
    FVector2D(75.0000, -25.0872), FVector2D(83.3333, -20.0466), FVector2D(91.6667, -14.3027),
    FVector2D(100.0000, -6.1205),
};
// Linear-interpolate a (span, chord) polyline at span Y. .X = span, .Y = chord.
double SampleMembrane(const FVector2D* Poly, int32 Count, double Y)
{
    if (Count < 2) return 0.0;
    if (Y <= Poly[0].X) return Poly[0].Y;
    for (int32 I = 1; I < Count; ++I)
    {
        if (Y <= Poly[I].X)
        {
            const double T = (Y - Poly[I - 1].X) / (Poly[I].X - Poly[I - 1].X);
            return Poly[I - 1].Y + T * (Poly[I].Y - Poly[I - 1].Y);
        }
    }
    return Poly[Count - 1].Y;
}
// Catmull-Rom interpolation (C1-smooth) through a uniformly-spaced station
// array. The solver returns 16 spanwise stations; linear interpolation between
// them leaves a slope discontinuity at every station boundary that reads as a
// fold/kink in the spar line outboard. A gentle beam should only ever curve.
double SampleStationField(const B2F_WingSection* Shape, int32 Count, double Station,
                          double B2F_WingSection::*Field)
{
    const double S = FMath::Clamp(Station, 0.0, double(Count - 1));
    const int32 I = FMath::FloorToInt(S);
    const double T = S - I;
    const int32 I0 = FMath::Clamp(I - 1, 0, Count - 1);
    const int32 I1 = FMath::Clamp(I,     0, Count - 1);
    const int32 I2 = FMath::Clamp(I + 1, 0, Count - 1);
    const int32 I3 = FMath::Clamp(I + 2, 0, Count - 1);
    const double P0 = Shape[I0].*Field;
    const double P1 = Shape[I1].*Field;
    const double P2 = Shape[I2].*Field;
    const double P3 = Shape[I3].*Field;
    const double T2 = T * T, T3 = T2 * T;
    return 0.5 * (2.0 * P1
        + (-P0 + P2) * T
        + (2.0 * P0 - 5.0 * P1 + 4.0 * P2 - P3) * T2
        + (-P0 + 3.0 * P1 - 3.0 * P2 + P3) * T3);
}
}

void UBorn2FlapWingMesh::InitializeWing(int32 Side, int32 Design)
{
    WingSide=Side; WingDesign=Design;
    SetCollisionEnabled(ECollisionEnabled::NoCollision);
    UV.Reset(); Colours.Reset(); Triangles.Reset(); RestVertices.Reset();
    auto Patch=[&](int32 NS,int32 NC,TFunction<FVector(double,double)> Position,FLinearColor Colour)
    {
        const int32 Base=RestVertices.Num();
        for(int32 S=0;S<=NS;++S) for(int32 C=0;C<=NC;++C)
        {
            const FVector P=Position(double(C)/NC,double(S)/NS);
            RestVertices.Add(FVector(P.X,Side*P.Y,P.Z));
            UV.Add(WingDesign==2
                ? FVector2D(0.007715591*P.Y+0.183350048, -0.019658545*P.X+0.241856176)
                : FVector2D((30-P.X)/95.,P.Y/105.));
            Colours.Add(Colour);
            if(S<NS && C<NC)
            {
                const int32 A=Base+S*(NC+1)+C,B=A+1,D=A+NC+1,E=D+1;
                if(Side>0) Triangles.Append({A,B,D,B,E,D}); else Triangles.Append({A,D,B,B,D,E});
            }
        }
    };
    const FLinearColor Ink(.025,.038,.055), Slate(.065,.09,.12), Teal(.015,.27,.30), Ivory(.88,.83,.66);
    if(Design==0)
    {
        // Broad folded arm with seven distinct, parallel slotted pinions.
        Patch(20,12,[](double U,double V){return FVector(FMath::Lerp(17.,12.,V)-U*FMath::Lerp(47.,37.,V),V*54.6,2.8*FMath::Sin(PI*U)*FMath::Sin(PI*V));},Ink);
        for(int32 I=0;I<7;++I)
        {
            const double X=13-I*6.,Tip=(63+10*FMath::Sin((I+1)*PI/9.))*1.4;
            Patch(24,6,[X,Tip](double U,double V){return FVector(X+2.5-3.7*V-U*FMath::Lerp(5.6,1.4,V),FMath::Lerp(40.6,Tip,V),1.2*FMath::Sin(PI*U));},I%3==0?Slate:Ink);
        }
    }
    else if(Design==1)
    {
        auto Ellipse=[&](FVector Centre,double RX,double RY,double Angle,FLinearColor Colour)
        {
            Patch(24,12,[=](double U,double V){
                const double Y=(2*V-1)*RY, X=(1-2*U)*RX*FMath::Sqrt(FMath::Max(.0001,1-FMath::Square(2*V-1)));
                const double A=FMath::DegreesToRadians(Angle);
                return Centre+FVector(X*FMath::Cos(A)-Y*FMath::Sin(A),X*FMath::Sin(A)+Y*FMath::Cos(A),1.5*FMath::Sin(PI*U)*FMath::Sin(PI*V));
            },Colour);
        };
        Ellipse(FVector(-4,38,0),22.5,42.5,8,Teal);
        for(int32 I=0;I<5;++I) Ellipse(FVector(-16-I*3,49+I*9,-1),( .43-I*.035)*50,10,15+I*7,I%2?Ivory:Teal);
    }
    else
        Patch(32,16,[](double U,double V){const double Y=100*V;return FVector(SampleMembrane(MembraneLE,13,Y)+U*(SampleMembrane(MembraneTE,13,Y)-SampleMembrane(MembraneLE,13,Y)),Y,0);},FLinearColor(.09,.24,.29));
    ApplyShape(nullptr);
    CreateMeshSection_LinearColor(0,Vertices,Triangles,Normals,UV,Colours,Tangents,false);
    SetMaterial(0,LoadObject<UMaterialInterface>(nullptr,WingDesign==2 ? TEXT("/Game/Birds/M_FalconWing") : TEXT("/Game/Birds/M_WingMembrane")));
}

void UBorn2FlapWingMesh::ApplyShape(const B2F_WingSection* Shape)
{
    if(Shape) { bReceivedShape=true; for(uint32 I=0;I<B2F_WING_STATIONS;++I) PeakBend=FMath::Max(PeakBend,FMath::Abs(Shape[I].bend_m)); }
    Vertices.SetNum(RestVertices.Num()); Normals.Init(FVector::ZeroVector,Vertices.Num()); Tangents.SetNum(Vertices.Num());
    for(int32 I=0;I<Vertices.Num();++I)
    {
        const FVector R=RestVertices[I];
        const double V=FMath::Clamp(FMath::Abs(R.Y)/(WingDesign==1?95.:(WingDesign==2?100.:102.)),0.,1.);
        double Camber=FMath::Lerp(.035,.025,V),Twist=FMath::DegreesToRadians(FMath::Lerp(5.,-2.,V)),Bend=0;
        if(Shape)
        {
            const double Station=FMath::Clamp(V*B2F_WING_STATIONS-.5,0.,double(B2F_WING_STATIONS-1));
            Camber=SampleStationField(Shape,B2F_WING_STATIONS,Station,&B2F_WingSection::camber);
            Twist=SampleStationField(Shape,B2F_WING_STATIONS,Station,&B2F_WingSection::twist_rad);
            // Passive flap bending: bend_m is the solver's root-clamped cantilever
            // deflection [m] (tip-up positive). *100 maps metres to mesh units; the
            // first station (span_fraction≈0.031) is the clamp ramp so the root
            // stays pinned and bends in smoothly.
            const double RootRamp=FMath::Clamp(V/Shape[0].span_fraction,0.,1.);
            Bend=SampleStationField(Shape,B2F_WING_STATIONS,Station,&B2F_WingSection::bend_m)*100*RootRamp;
        }
        const double Leading=WingDesign==2?SampleMembrane(MembraneLE,13,V*100):17-14*V;
        const double Trailing=WingDesign==2?SampleMembrane(MembraneTE,13,V*100):Leading-47.;
        const double Chord=Trailing-Leading;                                   // signed (LE forward +, TE aft -)
        const double ChordLen=-Chord;                                          // positive chord length
        const double U=FMath::Clamp(ChordLen>1.e-6?(Leading-R.X)/ChordLen:.5,0.,1.);
        // The leading-edge spar is the rigid reference: it only *bends* out of
        // plane (the Bend translation) — it never folds. The aeroelastic twist
        // therefore rotates the whole section rigidly about the LE spar, so the
        // membrane washes out behind it with no crease at any chordwise line.
        const double Pivot=Leading;                                            // leading-edge spar
        const double X=R.X-Pivot;                                              // 0 at LE, - toward TE
        const double Z=R.Z+4*U*(1-U)*Camber*ChordLen;                          // cambered-up arch (+Z)
        const double TwistRad=Twist;                                           // uniform section rotation
        const double C=FMath::Cos(TwistRad),S=FMath::Sin(TwistRad);
        // Displace along the wing's own flap normal (+Z), which rotates with the
        // shoulder, so the membrane flexes passively with the stroke instead of
        // holding a fixed world-vertical "wrist" against the airflow.
        Vertices[I]=FVector(Pivot+X*C-Z*S,R.Y,X*S+Z*C+Bend);
    }
    for(int32 I=0;I<Triangles.Num();I+=3)
    {
        const int32 A=Triangles[I],B=Triangles[I+1],C=Triangles[I+2];
        const FVector N=FVector::CrossProduct(Vertices[C]-Vertices[A],Vertices[B]-Vertices[A]);
        Normals[A]+=N; Normals[B]+=N; Normals[C]+=N;
    }
    for(int32 I=0;I<Vertices.Num();++I)
    {
        Normals[I]=Normals[I].GetSafeNormal(SMALL_NUMBER,FVector::UpVector);
        Tangents[I]=FProcMeshTangent(FVector::VectorPlaneProject(FVector(-1,0,0),Normals[I]).GetSafeNormal(),WingSide<0);
    }
    if(GetProcMeshSection(0)) UpdateMeshSection_LinearColor(0,Vertices,Normals,UV,Colours,Tangents);
}
void UBorn2FlapWingMesh::SetPaintTexture(UTexture2D* Texture)
{
    if(auto* M=CreateDynamicMaterialInstance(0)) { M->SetTextureParameterValue(TEXT("WingPaint"),Texture); M->SetScalarParameterValue(TEXT("PaintStrength"),Texture?1.f:0.f); }
}
bool UBorn2FlapWingMesh::HasValidDeformation()
{
    if(!bReceivedShape || PeakBend<.001 || Vertices.Num()<500) return false;
    const auto* Section=GetProcMeshSection(0); if(!Section || Section->ProcVertexBuffer.Num()!=UV.Num()) return false;
    for(int32 I=0;I<Vertices.Num();++I)
        if(Vertices[I].ContainsNaN() || !Normals[I].IsNormalized() || !Section->ProcVertexBuffer[I].UV0.Equals(UV[I],1.e-6)) return false;
    return true;
}
FVector UBorn2FlapWingMesh::GetWingTipLocal() const
{
    // Average the outboard-most span band of the rest membrane: the falcon's LE/TE
    // converge to a point while the prototype's tip is a chord edge, so a centroid
    // gives a stable probe anchor for every design. Sign follows WingSide (left -Y).
    const FVector Fallback(-6.f, WingSide * 100.f, 0.f);
    if (RestVertices.IsEmpty()) return Fallback;
    float MaxSpan = 0.f;
    for (const FVector& V : RestVertices) MaxSpan = FMath::Max(MaxSpan, FMath::Abs(V.Y));
    FVector Tip = FVector::ZeroVector; int32 N = 0;
    for (const FVector& V : RestVertices)
        if (FMath::Abs(V.Y) >= MaxSpan - 2.f) { Tip += V; ++N; }
    return N > 0 ? Tip / float(N) : Fallback;
}
FVector UBorn2FlapWingMesh::GetWingRootLocal() const
{
    // Centroid of the inboard span band (the shoulder), so the contact capsule
    // spans root -> tip regardless of design (falcon converges to a point, the
    // prototype keeps a chord edge). Sign follows WingSide (left -Y).
    const FVector Fallback(-2.f, 0.f, 0.f);
    if (RestVertices.IsEmpty()) return Fallback;
    FVector Root = FVector::ZeroVector; int32 N = 0;
    for (const FVector& V : RestVertices)
        if (FMath::Abs(V.Y) <= 3.f) { Root += V; ++N; }
    return N > 0 ? Root / float(N) : Fallback;
}