#pragma once
// Born2FlapInsectSwarm — populates the sky with manifold tiny insects:
// mantis, butterfly, dragonfly, lunar moth and a few big, brumming "bummer
// bugs". They are NOT a swarm around the pilot — each insect minds its own
// little life: a scattered population that lingers in a home territory, hops
// between perches, rides the wind and drifts where it pleases. The pilot just
// happens to fly through their world.
//
// Two layers, one hermetic class:
//   • the SWARM — hundreds of cheap instanced "speck" silhouettes (one
//     hierarchical-instanced component per species), each tethered to its own
//     territory, wandering, fluttering and riding the same wind the bird feels;
//   • the HEROES — a handful of close-up insects built from a shared body +
//     flapping wing meshes, going about their own foraging between random
//     perches (never orbiting the camera, never diving at the face).
//
// Meshes/materials are tiny procedural assets generated by
// Tools/create_insect_assets.py into /Game/Nature/Insects. If they are missing
// the actor logs a warning and stays dormant — the game never hard-fails.

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Born2FlapInsectSwarm.generated.h"

class UInstancedStaticMeshComponent;
class UStaticMeshComponent;
class USceneComponent;
class UMaterialInstanceDynamic;

UCLASS()
class BORN2FLAP_API ABorn2FlapInsectSwarm : public AActor
{
    GENERATED_BODY()

public:
    ABorn2FlapInsectSwarm();
    virtual void BeginPlay() override;
    virtual void Tick(float DeltaSeconds) override;

private:
    enum class EInsectType : uint8
    {
        Butterfly,
        Dragonfly,
        LunarMoth,
        Mantis,
        BummerBug,
        Count
    };

    struct FSpecies
    {
        const TCHAR* Name;
        FLinearColor Color;          // tint (body + wings, hero + swarm)
        FVector BodyScale;           // hero body mesh scale
        FVector WingScale;           // hero wing mesh scale
        float SwarmMin;              // swarm speck scale range
        float SwarmMax;
        float HeroScale;             // hero overall scale multiplier
        float Speed;                 // cruise cm/s
        float Agility;               // wander turn rate
        float FlapRate;              // hero wing flap Hz
        float FlapAmp;               // hero flap amplitude (degrees)
        int32 WingCount;             // 2 or 4
        int32 SwarmCount;            // how many swarm instances
        int32 HeroCount;             // how many close-up heroes
        bool bOpaqueWings;           // bummer bug elytra are solid, not membrane
        bool bBuzzer;                // erratic brumming motion
    };

    struct FBoid
    {
        EInsectType Type;
        FVector Pos;
        FVector Vel;
        FVector Home;
        double Phase;
        double Life;
        float Scale;
    };

    struct FHeroWing
    {
        UStaticMeshComponent* Mesh = nullptr;
        float Yaw = 0.f;
        FVector Scale = FVector::OneVector;
    };

    struct FHero
    {
        EInsectType Type;
        FVector Pos;
        FVector Vel;
        FVector Home;
        FVector Target;
        double Phase;
        double FlapPhase;
        float Scale;
        double NextRelocate = 0.0;
        USceneComponent* Root = nullptr;
        UStaticMeshComponent* Body = nullptr;
        TArray<FHeroWing> Wings;
    };

    double GroundHeight(const FVector& P) const;
    FVector WindAt(const FVector& P, double Time) const;
    FVector PickPerch(const FVector& Home) const;
    FVector PickVegetationHome(FRandomStream& R) const;

    void BuildSwarm();
    void BuildHeroes();
    FBoid SpawnBoid(FRandomStream& R, EInsectType Type);
    void SpawnHero(FRandomStream& R, const FSpecies& S, EInsectType Type);
    void TickSwarm(float DeltaSeconds);
    void TickHeroes(float DeltaSeconds);
    UMaterialInstanceDynamic* Tint(UMaterialInterface* Base, const FLinearColor& Color, float Alpha = 1.f);

    static const FSpecies* Species(EInsectType Type);

    UPROPERTY() TArray<TObjectPtr<UInstancedStaticMeshComponent>> Swarm;
    UPROPERTY() TArray<TObjectPtr<UMaterialInstanceDynamic>> SwarmMaterials;

    TArray<FBoid> Boids;
    TArray<FHero> Heroes;

    UStaticMesh* SpeckMesh = nullptr;
    UStaticMesh* WingMesh = nullptr;
    UStaticMesh* BodyMesh = nullptr;
    UMaterialInterface* WingMaterial = nullptr;
    UMaterialInterface* BodyMaterial = nullptr;

    bool bReady = false;
    static constexpr float HomeRadius = 1500.f;      // each insect's little territory around its plant
};