// Born2FlapMathWasmBackend — static b2f_math_* backend over wasm3.
//
// Implements the SAME C ABI as the desktop Haskell dylib
// (Native/include/born2flap_math.h) so Born2FlapMathBridge.cpp can bind it
// statically on iOS/Android where dlopen is forbidden. The Haskell MathCore is
// compiled once to born2flap_math.wasm (Tools/build-math-wasm.sh) and embedded
// here; wasm3 interprets it (no JIT → iOS-legal).
//
// WIP — requires the ghc-wasm toolchain + a vendored wasm3 to compile/verify.
// Not wired into Build.cs yet; see docs/ios-port.md.
//
// wasm3 dependency (MIT):
//   git submodule add https://github.com/wasm3/wasm3.git Native/ThirdParty/wasm3
#include "born2flap_math.h"

#if defined(__wasm__) || defined(B2F_WASM_BACKEND_ENABLED)

#include "wasm3.h"
#include "m3_env.h"
#include "m3_api_wasi.h"

#include <cstdint>
#include <cstring>

// Embedded module bytes (generated by Tools/build-math-wasm.sh → xxd -i).
// TODO(verify): include the generated header once the toolchain is installed:
//   #include "born2flap_math_wasm.inc"
static const uint8_t kBorn2FlapMathWasm[] = {};
static const uint32_t kBorn2FlapMathWasmLen = 0;

namespace
{
IM3Environment GEnv = nullptr;
IM3Runtime GRuntime = nullptr;
IM3Module GModule = nullptr;

IM3Function FnMalloc = nullptr;
IM3Function FnFree = nullptr;
IM3Function FnRuntimeInit = nullptr;
IM3Function FnRuntimeShutdown = nullptr;
IM3Function FnAbiVersion = nullptr;
IM3Function FnCreate = nullptr;
IM3Function FnDestroy = nullptr;
IM3Function FnStep = nullptr;
IM3Function FnSetNoise = nullptr;
IM3Function FnReconfigure = nullptr;
IM3Function FnGetWingShape = nullptr;

M3Result Find(const char* name, IM3Function* out)
{
    M3Result r = m3_FindFunction(out, GRuntime, name);
    if (r) { /* log */ }
    return r;
}

// Opaque pointer type inside the wasm32 linear memory. Contexts are GHC
// StablePtrs returned by the Haskell side and passed back untouched.
using WasmPtr = uint32_t;

// Allocate a POD struct in the WASM linear memory and copy host bytes in.
template <typename T>
WasmPtr Push(const T& value)
{
    // TODO(verify): use the linked malloc; a bump allocator is a fallback.
    WasmPtr p = 0;
    if (FnMalloc)
    {
        m3_GetResultsV(FnMalloc, &p);
        m3_CallV(FnMalloc, static_cast<uint32_t>(sizeof(T)));
    }
    uint8_t* mem = nullptr; uint32_t size = 0;
    if (m3_GetMemory(GRuntime, &mem, &size) || p + sizeof(T) > size)
        return 0;
    std::memcpy(mem + p, &value, sizeof(T));
    return p;
}

// Copy a POD struct back out of the WASM linear memory.
template <typename T>
void Pull(WasmPtr p, T& out)
{
    uint8_t* mem = nullptr; uint32_t size = 0;
    if (p && !m3_GetMemory(GRuntime, &mem, &size) && p + sizeof(T) <= size)
        std::memcpy(&out, mem + p, sizeof(T));
}

void Free(WasmPtr p)
{
    if (FnFree && p)
        m3_CallV(FnFree, p);
}

bool LoadWasm()
{
    if (GEnv || kBorn2FlapMathWasmLen == 0)
        return false;
    GEnv = m3_NewEnvironment();
    GRuntime = m3_NewRuntime(GEnv, 256 * 1024, nullptr);
    if (!GRuntime) return false;
    if (m3_ParseModule(GEnv, &GModule, kBorn2FlapMathWasm, kBorn2FlapMathWasmLen)) return false;
    if (m3_LoadModule(GRuntime, GModule)) return false;
    // GHC's WASI reactor needs WASI imports (clock, fd_write, …).
    m3_LinkWASI(GModule);

    Find("malloc", &FnMalloc);
    Find("free", &FnFree);
    Find("b2f_math_runtime_init", &FnRuntimeInit);
    Find("b2f_math_runtime_shutdown", &FnRuntimeShutdown);
    Find("b2f_math_abi_version", &FnAbiVersion);
    Find("b2f_math_create_firmware_vehicle", &FnCreate);
    Find("b2f_math_destroy_firmware_vehicle", &FnDestroy);
    Find("b2f_math_step_firmware_vehicle", &FnStep);
    Find("b2f_math_set_wind_phase_noise", &FnSetNoise);
    Find("b2f_math_reconfigure_firmware_vehicle", &FnReconfigure);
    Find("b2f_math_get_wing_shape", &FnGetWingShape);

    // TODO(verify): confirm the exact export names with wasm-objdump -x.
    // The C bridge may re-export them as b2f_math_* or hs_b2f_math_*.
    return FnCreate && FnStep;
}
} // namespace

extern "C" {

B2F_API uint32_t b2f_math_abi_version()
{
    if (!FnAbiVersion) return B2F_MATH_ABI_VERSION;
    uint32_t v = 0; m3_GetResultsV(FnAbiVersion, &v); m3_CallV(FnAbiVersion);
    return v;
}

B2F_API int32_t b2f_math_runtime_init()
{
    if (!GRuntime && !LoadWasm()) return 0;
    if (!FnRuntimeInit) return 1;
    int32_t r = 0; m3_GetResultsV(FnRuntimeInit, &r); m3_CallV(FnRuntimeInit);
    return r;
}

B2F_API void b2f_math_runtime_shutdown() {}

B2F_API B2F_MathContext* b2f_math_create_firmware_vehicle(const B2F_FirmwareConfig* config)
{
    if (!GRuntime) return nullptr;
    WasmPtr cfg = Push(*config);
    WasmPtr ctx = 0;
    m3_GetResultsV(FnCreate, &ctx);
    m3_CallV(FnCreate, cfg);
    Free(cfg);
    return reinterpret_cast<B2F_MathContext*>(static_cast<uintptr_t>(ctx));
}

B2F_API void b2f_math_destroy_firmware_vehicle(B2F_MathContext* context)
{
    if (FnDestroy && context)
        m3_CallV(FnDestroy, static_cast<uint32_t>(reinterpret_cast<uintptr_t>(context)));
}

B2F_API int32_t b2f_math_step_firmware_vehicle(
    B2F_MathContext* context,
    const B2F_PilotInput* pilot,
    const B2F_BodyState* body,
    B2F_FirmwareOutput* output)
{
    if (!context || !pilot || !body || !output) return 0;
    WasmPtr p = Push(*pilot);
    WasmPtr b = Push(*body);
    B2F_FirmwareOutput out{};
    WasmPtr o = Push(out);
    int32_t r = 0;
    m3_GetResultsV(FnStep, &r);
    m3_CallV(FnStep,
        static_cast<uint32_t>(reinterpret_cast<uintptr_t>(context)), p, b, o);
    Pull<B2F_FirmwareOutput>(o, *output);
    Free(p); Free(b); Free(o);
    return r;
}

B2F_API int32_t b2f_math_set_stabilization(B2F_MathContext*, uint32_t)
{
    // TODO(verify): export name if the Haskell FFI exposes it via the bridge.
    return 0;
}

B2F_API int32_t b2f_math_set_wind_phase_noise(B2F_MathContext* context, double noiseRadS)
{
    if (!context || !FnSetNoise) return 0;
    int32_t r = 0;
    m3_GetResultsV(FnSetNoise, &r);
    m3_CallV(FnSetNoise,
        static_cast<uint32_t>(reinterpret_cast<uintptr_t>(context)), noiseRadS);
    return r;
}

B2F_API int32_t b2f_math_reconfigure_firmware_vehicle(
    B2F_MathContext* context, const B2F_TuningConfig* tuning)
{
    if (!context || !tuning || !FnReconfigure) return 0;
    WasmPtr t = Push(*tuning);
    int32_t r = 0;
    m3_GetResultsV(FnReconfigure, &r);
    m3_CallV(FnReconfigure,
        static_cast<uint32_t>(reinterpret_cast<uintptr_t>(context)), t);
    Free(t);
    return r;
}

B2F_API int32_t b2f_math_get_wing_shape(
    B2F_MathContext* context, uint32_t capacity,
    B2F_WingSection* left, B2F_WingSection* right)
{
    // TODO(verify): array marshalling (left/right buffers) once FnGetWingShape
    // is confirmed exported.
    (void)context; (void)capacity; (void)left; (void)right;
    return 0;
}

} // extern "C"

#endif // defined(__wasm__) || B2F_WASM_BACKEND_ENABLED
