import re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'web' / '_code_ref'
HS_MODULE = re.compile(r'^\s*module\s+([A-Za-z0-9_.]+)')
HS_DATA = re.compile(r'^\s*(data|newtype|type|class)\s+(?:family\s+)?([A-Z][A-Za-z0-9_]+)')
HS_SIG = re.compile(r'^([a-z][A-Za-z0-9_]*)\s*::')
def scan_haskell(root):
    out = []
    for p in sorted((root / 'src').rglob('*.hs')):
        syms = []
        for i, line in enumerate(p.read_text(encoding='utf-8', errors='replace').splitlines(), 1):
            s = line.rstrip()
            m = HS_MODULE.match(s)
            if m: syms.append((m.group(1), 'module', i)); continue
            m = HS_DATA.match(s)
            if m: syms.append((m.group(2), m.group(1), i)); continue
            m = HS_SIG.match(s)
            if m: syms.append((m.group(1), 'sig', i))
        if syms: out.append((str(p.relative_to(root)), syms))
    return out
CPP_CLASS = re.compile(r'^\s*(?:class|struct)\s+(?:[A-Za-z_][A-Za-z0-9_:]*\s+)?([A-Z][A-Za-z0-9_]*)')
CPP_ENUM = re.compile(r'^\s*enum\s+(?:class\s+)?([A-Z][A-Za-z0-9_]*)')
CPP_METHOD = re.compile(r'([A-Za-z_][A-Za-z0-9_]*)::([A-Za-z_~][A-Za-z0-9_]*)\s*\(')
def scan_cpp(root, exts):
    out = []
    files = []
    for ext in exts: files += list(root.rglob(ext))
    for p in sorted(files, key=lambda f: str(f).lower()):
        syms = []
        for i, line in enumerate(p.read_text(encoding='utf-8', errors='replace').splitlines(), 1):
            s = line.rstrip()
            if len(s) > 500: continue
            m = CPP_CLASS.match(s)
            if m: syms.append((m.group(1), 'class', i)); continue
            m = CPP_ENUM.match(s)
            if m: syms.append((m.group(1), 'enum', i)); continue
            m = CPP_METHOD.search(s)
            if m: syms.append((f'{m.group(1)}::{m.group(2)}', 'method', i))
        if syms: out.append((str(p.relative_to(root)), syms))
    return out
RB_CLASS = re.compile(r'^\s*(?:class|module)\s+([A-Z][A-Za-z0-9_:]*)')
RB_DEF = re.compile(r'^\s*def\s+(?:self\.)?([a-z_][A-Za-z0-9_!?=]*)')
def scan_ruby(root):
    out = []
    for p in sorted(root.rglob('*.rb')):
        syms = []
        for i, line in enumerate(p.read_text(encoding='utf-8', errors='replace').splitlines(), 1):
            s = line.rstrip()
            m = RB_CLASS.match(s)
            if m: syms.append((m.group(1), 'class', i)); continue
            m = RB_DEF.match(s)
            if m: syms.append((m.group(1), 'def', i))
        if syms: out.append((str(p.relative_to(root)), syms))
    return out
PY_CLASS = re.compile(r'^\s*class\s+(\w+)')
PY_DEF = re.compile(r'^\s*(?:async\s+)?def\s+(\w+)')
def scan_python(root):
    out = []
    for p in sorted(root.rglob('*.py')):
        syms = []
        for i, line in enumerate(p.read_text(encoding='utf-8', errors='replace').splitlines(), 1):
            s = line.rstrip()
            m = PY_CLASS.match(s)
            if m: syms.append((m.group(1), 'class', i)); continue
            m = PY_DEF.match(s)
            if m: syms.append((m.group(1), 'def', i))
        if syms: out.append((str(p.relative_to(root)), syms))
    return out
LANGS = [
    ('mathcore', 'Haskell MathCore', scan_haskell, ROOT / 'MathCore'),
    ('native', 'Native C/C++', lambda r: scan_cpp(r, ['*.h', '*.cpp']), ROOT / 'Native'),
    ('unreal', 'Unreal Engine C++', lambda r: scan_cpp(r, ['*.h', '*.cpp']), ROOT / 'Unreal' / 'Born2Flap' / 'Source'),
    ('brain', 'Brain (Ruby)', scan_ruby, ROOT / 'Brain' / 'lib'),
    ('tools', 'Tools (Python)', scan_python, ROOT / 'Tools'),
]
def render_lang_page(title, entries):
    lines = ['# ' + title + ' - symbol reference', '', '> Auto-generated by Tools/gen_code_reference.py - do not edit by hand.', '']
    nf = len(entries); ns = sum(len(s) for _, s in entries)
    lines.append('**' + str(nf) + ' files / ' + str(ns) + ' symbols**'); lines.append('')
    for path, syms in entries:
        lines.append('## `' + path + '`'); lines.append('')
        for sym, kind, ln in syms:
            lines.append('- `' + sym + '` - *' + kind + '* (line ' + str(ln) + ')')
        lines.append('')
    return '\n'.join(lines)
def _anchor(path):
    return path.lower().replace('/', '').replace('\\\\', '').replace('.', '-').replace('_', '-')
def main():
    OUT.mkdir(parents=True, exist_ok=True)
    all_entries = []
    for key, title, fn, root in LANGS:
        entries = fn(root)
        all_entries.append((key, title, entries))
        (OUT / (key + '.md')).write_text(render_lang_page(title, entries), encoding='utf-8')
        print('wrote ' + key + '.md  (' + str(len(entries)) + ' files, ' + str(sum(len(s) for _, s in entries)) + ' symbols)')
    lines = ['# Full API index', '', 'Every source file and symbol, grouped by subsystem.', '', '> Auto-generated by Tools/gen_code_reference.py.', '']
    tf = 0; ts = 0
    for key, title, entries in all_entries:
        tf += len(entries); ts += sum(len(s) for _, s in entries)
        lines.append('## ' + title); lines.append('')
        for path, syms in entries:
            lines.append('- [`' + path + '`](' + key + '/#' + _anchor(path) + ') - ' + str(len(syms)) + ' symbols')
        lines.append('')
    lines.append('**Totals: ' + str(tf) + ' files / ' + str(ts) + ' symbols**')
    (OUT / 'api.md').write_text('\n'.join(lines), encoding='utf-8')
    print('wrote api.md  (' + str(tf) + ' files, ' + str(ts) + ' symbols total)')
if __name__ == '__main__':
    main()
